### ISSUE TITLE
Prefer inline type imports 

### ISSUE THREAD

**Issue by dglsparsons** [vercel/style-guide#54] opened 2022-11-07 10:08 UTC
https://github.com/import-js/eslint-plugin-import/issues/2469 

Would much prefer 
```typescript 
import { type Foo } from 'some/package` 
```
over 
```typescript 
import type { Foo } from 'some/package`
```

as it keeps the single import line, and all related entries together. 

https://github.com/import-js/eslint-plugin-import/pull/2475 looks like it may block this though.

**Comment by mrmckeb** [comment] 2022-11-07 23:32
Thanks @dglsparsons! We're waiting for the next release to enable this - but it's definitely on our list.

Closing as a duplicate of this: https://github.com/vercel/style-guide/issues/38

**Closed as not planned by mrmckeb** 2022-11-07 23:32 UTC

**Comment by dglsparsons** [comment] 2022-11-08 07:02
Oh, good spot. I checked to see if it existed already. Must have somehow missed the other issue 🤦
